site_name: FDUGuideBook
site_url: https://docs.fduguidebook.com
repo_url: https://github.com/FDUGuideBook/FDUGuideBook
edit_uri: edit/master/docs/
repo_name: FDUGuideBook

nav:
  - 首页: index.md
  - 工学:
    - 工学/index.md
    - 工学/电子DIY基础.md
    - 工学/嵌入式软件.md
    - 工学/机器人学.md
    - 工学/RoboMaster.md
    - 泔水桶:
      - 工学/泔水桶/3D打印.md

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    logo: material/map
  favicon: images/blueberries.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.indexes
    - navigation.footer
    - navigation.tabs
    - toc.follow
    - content.action.edit
    - content.action.view
    
plugins:
  - tags
  - meta: 
      meta_file: .meta.yml
  - search:
      lang:
        - en
        - zh
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
      type: date
  - git-committers:
      repository: FDUGuideBook/FDUGuideBook
      branch: master
      enabled: !ENV [CI, false]

markdown_extensions:
  
  # Python Markdown
  - admonition
  - attr_list
  - footnotes
  - tables
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Python Markdown Extensions
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  status:
    <identifier>: <description>
