site_name: FDUGuideBook
site_url: https://docs.fduguidebook.com
repo_url: https://github.com/FDUGuideBook/FDUGuideBook
edit_uri: edit/master/docs/
repo_name: FDUGuideBook

nav:
    - 欢迎来到复旦冒险指南: index.md
    - 知识库动态: 知识库动态.md
    - 计算机类:
        - 计算机类: 计算机类/index.md
        - 深度学习&大模型方向入门:
            - 入门基础: 计算机类\深度学习&大模型方向入门\入门基础.md
        - 区块链方向:
            - 部分方向与发展路径: 计算机类\区块链方向\部分方向与发展路径.md
            - 区块链入门须知: 计算机类\区块链方向\区块链入门须知.md
            - 快速上手小清单: 计算机类\区块链方向\快速上手小清单.md
        - AI应用开发:
            - 学习路径: 计算机类\AI应用开发\学习路径.md
    - 电子类:
        - 电子类: 电子类/index.md
        - 如何做一个平衡小车？: 电子类\如何做一个平衡小车？.md
        - 如何准备电赛？: 电子类\如何准备电赛？.md
        - 嵌入式开发: 电子类\嵌入式开发.md
        - 如何找到开源项目？: 电子类\如何找到开源项目？.md
        - 电子DIY基础: 电子类\电子DIY基础.md
    - 微电子:
        - 微电子: 微电子/index.md
        - 数字设计入门: 微电子\数字设计入门.md
        - EDA: 微电子\EDA.md
        - FPGA开发？: 微电子\FPGA开发？.md
    - 人工智能:
        - 人工智能: 人工智能/index.md
        - 具身智能课程和项目: 人工智能\具身智能课程和项目.md
        - FDU CS自学指南: 人工智能\FDU CS自学指南.md
        - 科研: 人工智能\科研.md
        - 项目: 人工智能\项目.md
        - 关于入门基础的补充: 人工智能\关于入门基础的补充.md
    - 泔水桶:
        - 泔水桶: 泔水桶/index.md
        - 菜鸟教程: 泔水桶\菜鸟教程.md
        - Windows扫盲:
            - 用户、用户名与多用户: 泔水桶\Windows扫盲\用户、用户名与多用户.md
        - Chisel: 泔水桶\Chisel.md
        - SolidWorks: 泔水桶\SolidWorks.md
        - Docker: 泔水桶\Docker.md
        - Obsidian: 泔水桶\Obsidian.md
        - RoboMaster: 泔水桶\RoboMaster.md
        - STM32: 泔水桶\STM32.md
        - V2ray: 泔水桶\V2ray.md
        - Markdown: 泔水桶\Markdown.md
        - Stack Overflow: 泔水桶\Stack Overflow.md
        - FPGA: 泔水桶\FPGA.md
        - Verilog HDL: 泔水桶\Verilog HDL.md
        - Vivado软件: 泔水桶\Vivado软件.md
        - 数字逻辑基础: 泔水桶\数字逻辑基础.md
        - 模拟电子学基础: 泔水桶\模拟电子学基础.md
        - Linux: 泔水桶\Linux.md
        - Latex: 泔水桶\Latex.md
        - C语言: 泔水桶\C语言.md
        - Z-Library: 泔水桶\Z-Library.md
    - 泔水桶: 泔水桶.md

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    logo: material/map
  favicon: images/blueberries.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.indexes
    - navigation.footer
    - navigation.tabs
    - toc.follow
    - content.action.edit
    - content.action.view
    
plugins:
  - tags
  - meta: 
      meta_file: .meta.yml
  - search:
      lang:
        - en
        - zh
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
      type: date
  - git-committers:
      repository: FDUGuideBook/FDUGuideBook
      branch: master
      enabled: !ENV [CI, false]

markdown_extensions:
  
  # Python Markdown
  - admonition
  - attr_list
  - footnotes
  - tables
  - md_in_html
  - def_list
  # Python Markdown Extensions
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  status:
    <identifier>: <description>
